spare_part_outbounds = {'name': 'spare_part_outbounds', 'customFields': [
    {'id': 'spare_part_outbounds_领用仓库', 'type': 'TEXT', 'colName': 'shelf', 'fieldName': 'shelf', 'title': '领用仓库',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_part_outbounds_领用工厂', 'type': 'TEXT', 'colName': 'factory', 'fieldName': 'factory', 'title': '领用工厂',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_part_outbounds_领用时间', 'type': 'DATETIME', 'colName': 'time', 'fieldName': 'time', 'title': '领用时间',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultDatetime': None}], 'isPublish': True}
spare_part_receipts = {'name': 'spare_part_receipts', 'customFields': [
    {'id': 'spare_part_receipts_入库仓库', 'type': 'TEXT', 'colName': 'shelf', 'fieldName': 'shelf', 'title': '入库仓库',
     'deletable': False, 'required': True, 'fieldRatio': 100.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_part_receipts_入库工厂', 'type': 'TEXT', 'colName': 'factory', 'fieldName': 'factory', 'title': '入库工厂',
     'deletable': False, 'required': True, 'fieldRatio': 100.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_part_receipts_入库时间', 'type': 'DATETIME', 'colName': 'time', 'fieldName': 'time', 'title': '入库时间',
     'deletable': True, 'required': False, 'fieldRatio': 100.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultDatetime': None}], 'isPublish': True}
spare_parts = {'name': 'spare_parts', 'customFields': [
    {'id': 'spare_parts_备件名称', 'type': 'TEXT', 'colName': 'name', 'fieldName': 'name', 'title': '备件名称',
     'deletable': False, 'required': True, 'fieldRatio': 100.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_parts_备件类型', 'type': 'SINGLE_SELECTION', 'colName': 'type', 'fieldName': 'type', 'title': '备件类型',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultSelection': None, 'candidates': ['生产设备']},
    {'id': 'spare_parts_备件型号', 'type': 'TEXT', 'colName': 'model', 'fieldName': 'model', 'title': '备件型号',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_parts_生产厂家', 'type': 'TEXT', 'colName': 'manufacturer', 'fieldName': 'manufacturer', 'title': '生产厂家',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_parts_经销商', 'type': 'TEXT', 'colName': 'distributor', 'fieldName': 'distributor', 'title': '经销商',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_parts_备件描述', 'type': 'TEXT', 'colName': 'desc', 'fieldName': 'desc', 'title': '备件描述',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'spare_parts_附件', 'type': 'ATTACHMENT', 'colName': None, 'fieldName': 'attachments', 'title': '附件',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': '上传附件',
     'formula': None, 'sizeLimit': 100, 'countLimit': 5},
    {'id': 'spare_parts_图片', 'type': 'IMAGE', 'colName': None, 'fieldName': 'images', 'title': '图片', 'deletable': True,
     'required': False, 'fieldRatio': 100.0, 'isOrigin': True, 'hidden': False, 'prompt': '上传图片', 'formula': None,
     'sizeLimit': 100, 'countLimit': 5},
    {'id': 'spare_parts_单价', 'type': 'NUMBER', 'colName': 'price', 'fieldName': 'price', 'title': '单价',
     'deletable': False, 'required': True, 'fieldRatio': 100.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultNumber': None, 'digit': 2, 'showMoney': False},
    {'id': 'f881c575aeab40f19093f57c64fd52da', 'type': 'NUMBER', 'colName': None, 'fieldName': None, 'title': '预计净残值率',
     'deletable': True, 'required': False, 'fieldRatio': 25.0, 'isOrigin': False, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultNumber': None, 'digit': None, 'showMoney': False},
    {'id': '8e8540d4e51649aca1f4260b8068e91b', 'type': 'NUMBER', 'colName': None, 'fieldName': None, 'title': '预计使用年限',
     'deletable': True, 'required': False, 'fieldRatio': 25.0, 'isOrigin': False, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultNumber': None, 'digit': None, 'showMoney': False},
    {'id': 'ec916274c7de43ed9f7e4b0f15b336b9', 'type': 'NUMBER', 'colName': None, 'fieldName': None, 'title': '固定资产原值',
     'deletable': True, 'required': False, 'fieldRatio': 25.0, 'isOrigin': False, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultNumber': None, 'digit': None, 'showMoney': False},
    {'id': 'ddaf5f37d7dd4b33b10d8355e41f3242', 'type': 'NUMBER', 'colName': None, 'fieldName': None, 'title': '已使用年数',
     'deletable': True, 'required': False, 'fieldRatio': 25.0, 'isOrigin': False, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultNumber': None, 'digit': None, 'showMoney': False},
    {'id': 'db23b8b5f43748a19ad5278f75befca1', 'type': 'NUMBER', 'colName': None, 'fieldName': None, 'title': '年折旧率',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': False, 'hidden': False, 'prompt': None,
     'formula': '{"args": ["id_f881c575aeab40f19093f57c64fd52da", "id_8e8540d4e51649aca1f4260b8068e91b"], "formula": "DEPRECIATED_RATE"}',
     'defaultNumber': None, 'digit': None, 'showMoney': False},
    {'id': 'e87edaf485a748018c7a378005b5f387', 'type': 'NUMBER', 'colName': None, 'fieldName': None, 'title': '折余价值',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': False, 'hidden': False, 'prompt': None,
     'formula': '{"args": ["id_ec916274c7de43ed9f7e4b0f15b336b9", "id_db23b8b5f43748a19ad5278f75befca1", "id_ddaf5f37d7dd4b33b10d8355e41f3242"], "formula": "DEPRECIATED_VALUE"}',
     'defaultNumber': None, 'digit': None, 'showMoney': False}], 'isPublish': True}
thing_inspection_rules = {'name': 'thing_inspection_rules', 'customFields': [
    {'id': 'thing_inspection_rules_巡检方案名称', 'type': 'TEXT', 'colName': 'name', 'fieldName': 'name', 'title': '巡检方案名称',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}}],
                          'isPublish': True}
thing_inspections = {'name': 'thing_inspections', 'customFields': [], 'isPublish': True}
thing_inspections_feedback = {'name': 'thing_inspections_feedback', 'customFields': [
    {'id': 'thing_inspections_feedback_巡检完成时间', 'type': 'DATETIME', 'colName': 'end_at', 'fieldName': 'endAt',
     'title': '巡检完成时间', 'deletable': True, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultDatetime': None}], 'isPublish': True}
thing_maintenance = {'name': 'thing_maintenance', 'customFields': [], 'isPublish': True}
thing_maintenance_feedback = {'name': 'thing_maintenance_feedback', 'customFields': [
    {'id': 'thing_maintenance_feedback_结束时间', 'type': 'DATETIME', 'colName': 'end_at', 'fieldName': 'endAt',
     'title': '结束时间', 'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultDatetime': None},
    {'id': 'thing_maintenance_feedback_备注', 'type': 'TEXT', 'colName': 'remarks', 'fieldName': 'remarks', 'title': '备注',
     'deletable': False, 'required': False, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'thing_maintenance_feedback_备件费', 'type': 'NUMBER', 'colName': 'spare_part_costs',
     'fieldName': 'sparePartCosts', 'title': '备件费', 'deletable': False, 'required': False, 'fieldRatio': 50.0,
     'isOrigin': True, 'hidden': False, 'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 0,
     'showMoney': False}, {'id': 'thing_maintenance_feedback_材料费', 'type': 'NUMBER', 'colName': 'material_costs',
                           'fieldName': 'materialCosts', 'title': '材料费', 'deletable': False, 'required': False,
                           'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None, 'formula': None,
                           'defaultNumber': None, 'digit': 0, 'showMoney': False},
    {'id': 'thing_maintenance_feedback_人工费', 'type': 'NUMBER', 'colName': 'labor_costs', 'fieldName': 'laborCosts',
     'title': '人工费', 'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': False},
    {'id': 'thing_maintenance_feedback_其他费用', 'type': 'NUMBER', 'colName': 'other_costs', 'fieldName': 'otherCosts',
     'title': '其他费用', 'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': False},
    {'id': 'thing_maintenance_feedback_保养结果', 'type': 'TEXT', 'colName': None, 'fieldName': 'result', 'title': '保养结果',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 1, 'max': 1000}},
    {'id': 'thing_maintenance_feedback_保养图片', 'type': 'IMAGE', 'colName': None, 'fieldName': 'images', 'title': '保养图片',
     'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': '保养图片',
     'formula': None, 'sizeLimit': 100, 'countLimit': 5}], 'isPublish': True}
thing_maintenance_rules = {'name': 'thing_maintenance_rules', 'customFields': [
    {'id': 'thing_maintenance_rules_保养方案名称', 'type': 'TEXT', 'colName': 'name', 'fieldName': 'name', 'title': '保养方案名称',
     'deletable': False, 'required': True, 'fieldRatio': 100.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'thing_maintenance_rules_保养等级', 'type': 'SINGLE_SELECTION', 'colName': 'level', 'fieldName': 'level',
     'title': '保养等级', 'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultSelection': None, 'candidates': ['一级保养', '二级保养', '三级保养']},
    {'id': 'thing_maintenance_rules_保养频次', 'type': 'TEXT', 'colName': 'frequency', 'fieldName': 'frequency',
     'title': '保养频次', 'deletable': True, 'required': False, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None,
     'formula': None, 'isOrigin': True, 'defaultText': None, 'isSingleLine': True,
     'wordCountLimit': {'min': 0, 'max': 100}}], 'isPublish': True}
thing_repairs = {'name': 'thing_repairs', 'customFields': [
    {'id': 'thing_repairs_申请部门', 'type': 'TEXT', 'colName': 'report_department', 'fieldName': 'reportDepartment',
     'title': '申请部门', 'deletable': False, 'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None,
     'formula': None, 'isOrigin': True, 'defaultText': None, 'isSingleLine': True,
     'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'thing_repairs_故障描述', 'type': 'TEXT', 'colName': 'fault_desc', 'fieldName': 'faultDesc', 'title': '故障描述',
     'deletable': False, 'required': True, 'fieldRatio': 100.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'thing_repairs_故障图片', 'type': 'IMAGE', 'colName': None, 'fieldName': 'faultImages', 'title': '故障图片',
     'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': '故障图片',
     'formula': None, 'sizeLimit': 100, 'countLimit': 5}], 'isPublish': True}
thing_repairs_feedback = {'name': 'thing_repairs_feedback', 'customFields': [
    {'id': 'thing_repairs_feedback_维修完成时间', 'type': 'DATETIME', 'colName': 'finished_at', 'fieldName': 'finishedAt',
     'title': '维修完成时间', 'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultDatetime': None},
    {'id': 'thing_repairs_feedback_备件费', 'type': 'NUMBER', 'colName': 'spare_part_costs', 'fieldName': 'sparePartCosts',
     'title': '备件费', 'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': True},
    {'id': 'thing_repairs_feedback_维修费用', 'type': 'DESCRIPTION', 'colName': None, 'fieldName': None, 'title': '维修费用',
     'deletable': True, 'required': False, 'fieldRatio': 100.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultDesc': None},
    {'id': 'thing_repairs_feedback_材料费', 'type': 'NUMBER', 'colName': 'material_costs', 'fieldName': 'materialCosts',
     'title': '材料费', 'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': True},
    {'id': 'thing_repairs_feedback_人工费', 'type': 'NUMBER', 'colName': 'labor_costs', 'fieldName': 'laborCosts',
     'title': '人工费', 'deletable': True, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': True},
    {'id': 'thing_repairs_feedback_其他费用', 'type': 'NUMBER', 'colName': 'other_costs', 'fieldName': 'otherCosts',
     'title': '其他费用', 'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': True},
    {'id': 'thing_repairs_feedback_维修结果', 'type': 'TEXT', 'colName': None, 'fieldName': 'result', 'title': '维修结果',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 1, 'max': 1000}}],
                          'isPublish': True}
things = {'name': 'things', 'customFields': [
    {'id': 'things_设备名称', 'type': 'TEXT', 'colName': 'name', 'fieldName': 'name', 'title': '设备名称', 'deletable': False,
     'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None, 'isOrigin': True,
     'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'things_设备编码', 'type': 'TEXT', 'colName': 'code', 'fieldName': 'code', 'title': '设备编码', 'deletable': False,
     'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None, 'isOrigin': True,
     'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'things_设备位置', 'type': 'TEXT', 'colName': 'location', 'fieldName': 'location', 'title': '设备位置',
     'deletable': True, 'required': False, 'fieldRatio': 100.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'things_设备型号', 'type': 'TEXT', 'colName': 'model', 'fieldName': 'model', 'title': '设备型号', 'deletable': False,
     'required': True, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None, 'isOrigin': True,
     'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'things_负责人', 'type': 'CONTACT', 'colName': 'contact', 'fieldName': 'contact', 'title': '负责人',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultContact': None},
    {'id': 'things_手机号码', 'type': 'TEXT', 'colName': 'phone', 'fieldName': 'phone', 'title': '手机号码', 'deletable': True,
     'required': False, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None, 'isOrigin': True,
     'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'things_生产厂家', 'type': 'TEXT', 'colName': 'manufacturer', 'fieldName': 'manufacturer', 'title': '生产厂家',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'things_经销商', 'type': 'TEXT', 'colName': 'distributor', 'fieldName': 'distributor', 'title': '经销商',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'hidden': False, 'prompt': None, 'formula': None,
     'isOrigin': True, 'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'things_采购日期', 'type': 'DATETIME', 'colName': 'purchased_at', 'fieldName': 'purchasedAt', 'title': '采购日期',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultDatetime': None},
    {'id': 'things_启用日期', 'type': 'DATETIME', 'colName': 'activated_at', 'fieldName': 'activatedAt', 'title': '启用日期',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultDatetime': None},
    {'id': 'things_关联附件', 'type': 'ATTACHMENT', 'colName': None, 'fieldName': 'attachments', 'title': '关联附件',
     'deletable': True, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'sizeLimit': 100, 'countLimit': 5},
    {'id': 'things_设备图片', 'type': 'IMAGE', 'colName': None, 'fieldName': 'images', 'title': '设备图片', 'deletable': True,
     'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None, 'formula': None,
     'sizeLimit': 100, 'countLimit': 5},
    {'id': 'things_设备描述', 'type': 'TEXT', 'colName': 'desc', 'fieldName': 'desc', 'title': '设备描述', 'deletable': True,
     'required': False, 'fieldRatio': 100.0, 'hidden': False, 'prompt': None, 'formula': None, 'isOrigin': True,
     'defaultText': None, 'isSingleLine': True, 'wordCountLimit': {'min': 0, 'max': 100}},
    {'id': 'things_设备类别', 'type': 'SINGLE_SELECTION', 'colName': 'category', 'fieldName': 'category', 'title': '设备类别',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultSelection': None, 'candidates': ['生产设备', "辅助设备", "冷却设备"]},
    {'id': 'things_品牌', 'type': 'SINGLE_SELECTION', 'colName': 'brand', 'fieldName': 'brand', 'title': '品牌',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultSelection': None, 'candidates': ['喜临门', "惠普", '牧马人']},
    {'id': 'things_使用工厂', 'type': 'SINGLE_SELECTION', 'colName': 'factory', 'fieldName': 'factory', 'title': '使用工厂',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultSelection': None, 'candidates': ['喜临门', "生产工厂", "调试工厂"]},
    {'id': 'things_用途', 'type': 'SINGLE_SELECTION', 'colName': 'purpose', 'fieldName': 'purpose', 'title': '用途',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultSelection': None, 'candidates': ['生产', "冷却", "加热"]},
    {'id': 'things_设备状态', 'type': 'SINGLE_SELECTION', 'colName': 'status', 'fieldName': 'status', 'title': '设备状态',
     'deletable': False, 'required': True, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultSelection': None, 'candidates': ['使用中', "废用中", "闲置"]},
    {'id': 'things_采购价格(固定资产原值)', 'type': 'NUMBER', 'colName': 'purchased_price', 'fieldName': 'purchasedPrice',
     'title': '采购价格(固定资产原值)', 'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True,
     'hidden': False, 'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': True},
    {'id': 'things_预计使用年限', 'type': 'NUMBER', 'colName': 'years_of_use', 'fieldName': 'yearsOfUse', 'title': '预计使用年限',
     'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': False},
    {'id': 'things_已使用年数', 'type': 'NUMBER', 'colName': 'used_year', 'fieldName': 'UsedYear', 'title': '已使用年数',
     'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False, 'prompt': None,
     'formula': None, 'defaultNumber': None, 'digit': 0, 'showMoney': False},
    {'id': 'things_预计净产值率', 'type': 'NUMBER', 'colName': 'predict_residual_rate', 'fieldName': 'predictResidualRate',
     'title': '预计净产值率', 'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': 2, 'showMoney': False},
    {'id': 'things_年折旧率', 'type': 'NUMBER', 'colName': 'depreciation_rate', 'fieldName': 'depreciationRate',
     'title': '年折旧率', 'deletable': False, 'required': False, 'fieldRatio': 50.0, 'isOrigin': True, 'hidden': False,
     'prompt': None, 'formula': None, 'defaultNumber': None, 'digit': None, 'showMoney': False}], 'isPublish': True}
form_list = [spare_part_outbounds, spare_part_receipts, spare_parts, thing_inspection_rules, thing_inspections,
             thing_inspections_feedback, thing_maintenance, thing_maintenance_feedback, thing_maintenance_rules,
             thing_repairs, thing_repairs_feedback, things]
